default: &default
  adapter: postgresql
  encoding: unicode
  pool: 40
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: root

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
